---
- hosts: node
  vars_files:
  - env_variables
  tasks:
  - name: Copying token to worker nodes...
    copy: src=./{{ token_file }} dest=/home/ubuntu/join_token

  - name: Joining worker nodes with kubernetes master...
    become: yes
    shell: |
     kubeadm reset -f
     cat /home/ubuntu/join_token | tail -2 > kubeadmjoin.sh
     sh kubeadmjoin.sh