stages:
  - build
#  - test
#  - publish
  - deploy

build:
  stage: build
  before_script:
    - if [ -z `command -v docker` ]; then echo "install docker on gitlab runner or use an image to build"; else docker ps; fi
  script:
    - docker build -t appnode .
  only:
    - develop

#publish_to_intenal_registry:
#  stage: publish
#  before_script:
#    - aws ecr get-login --region us-east-1 --no-include-email
#  script:
#    - docker tag appnode ${ECR_REPO_URL}/appnode
#    - docker push ${ECR_REPO_URL}/appnode
#  only:
#    - develop

deploy:
  stage: deploy
#  before_script:
#    - aws ecr get-login --region us-east-1 --no-include-email
#    - docker pull ${ECR_REPO_URL}/appnode
  script:
    - helm install appnode
  only:
    - develop
